# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Copyright © Simon ANDRÉ <simon@emencia.com> synw (https://github.com/synw/)
# project: SkiiSchoolPlatform
# github: https://github.com/boot-sandre/skii-school-platform/
# template: https://github.com/synw/django-spaninja
from main.api import api


def test_api_json_openapi(admin_client):
    """Test endpoint which provide autogenerated openapi.json"""
    response = admin_client.get(f"{api.root_path}{api.openapi_url[1:]}")
    assert response.status_code == 200
    assert response.json()["info"]["title"] == "NinjaAPI"


def test_api_docs(admin_client):
    """Test the /api/docs endpoint"""
    response = admin_client.get(f"{api.root_path}{api.docs_url[1:]}")
    assert response.status_code == 200


def test_visitor_cannot_access_api(client):
    """Test that visitor cannot access API"""
    response = client.get(f"{api.root_path}{api.docs_url[1:]}")
    assert response.status_code == 302
    assert response.url == f"/admin/login/?next={api.root_path}{api.docs_url[1:]}"
