# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Copyright © Simon ANDRÉ <simon@emencia.com> synw (https://github.com/synw/)
# project: SkiiSchoolPlatform
# github: https://github.com/boot-sandre/skii-school-platform/
# template: https://github.com/synw/django-spaninja
# Generated by Django 4.2.5 on 2023-09-28 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lessonevent",
            old_name="uuid",
            new_name="guid",
        ),
        migrations.RenameField(
            model_name="locationresource",
            old_name="uuid",
            new_name="guid",
        ),
        migrations.RenameField(
            model_name="moneyresource",
            old_name="uuid",
            new_name="guid",
        ),
        migrations.RenameField(
            model_name="studentagent",
            old_name="uuid",
            new_name="guid",
        ),
        migrations.RenameField(
            model_name="teacheragent",
            old_name="uuid",
            new_name="guid",
        ),
        migrations.RenameField(
            model_name="timeresource",
            old_name="uuid",
            new_name="guid",
        ),
        migrations.RenameField(
            model_name="visualalbum",
            old_name="uuid",
            new_name="guid",
        ),
        migrations.RenameField(
            model_name="visualelement",
            old_name="uuid",
            new_name="guid",
        ),
        migrations.RenameField(
            model_name="visualpicture",
            old_name="uuid",
            new_name="guid",
        ),
    ]
