# Generated by Django 4.2.6 on 2023-10-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0002_rename_uuid_lessonevent_guid_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lessonevent",
            name="check_no_overlap",
        ),
        migrations.AddConstraint(
            model_name="lessonevent",
            constraint=models.CheckConstraint(
                check=models.Q(("start__lt", models.F("stop"))), name="check_no_overlap"
            ),
        ),
    ]
