# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Copyright © Simon ANDRÉ <simon@emencia.com> synw (https://github.com/synw/)
# project: SkiiSchoolPlatform
# github: https://github.com/boot-sandre/skii-school-platform/
# template: https://github.com/synw/django-spaninja
# Generated by Django 4.2.6 on 2023-10-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0002_rename_uuid_lessonevent_guid_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lessonevent",
            name="check_no_overlap",
        ),
        migrations.AddConstraint(
            model_name="lessonevent",
            constraint=models.CheckConstraint(
                check=models.Q(("start__lt", models.F("stop"))), name="check_no_overlap"
            ),
        ),
    ]
