# Generated by Django 4.2.6 on 2023-10-09 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("platform", "0003_remove_lessonevent_check_no_overlap_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentagent",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teacheragent",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"is_active": True, "is_staff": True},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
