# Generated by Django 4.2.4 on 2023-08-12 20:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skii_school_core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="currencyressource",
            old_name="values",
            new_name="factor",
        ),
        migrations.AddField(
            model_name="currencyressource",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=12,
                verbose_name="Price factor against dollars",
            ),
        ),
    ]
