# Generated by Django 4.2.4 on 2023-08-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skii_school_core", "0002_rename_values_currencyressource_factor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyagent",
            name="user",
        ),
    ]
