# Generated by Django 4.2.4 on 2023-08-12 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("skii_school_core", "0004_alter_event_start_alter_event_stop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="start",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Start time"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="stop",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Stop time"
            ),
        ),
    ]
